### PR TITLE
[#16] Prefix for command line option parsers

### PR DESCRIPTION
**Pull request by larskuhtz**
This pull request solves issue #16.

### CODE REVIEW

**Comment by jonsterling** [comment]
Good thinking!

Perhaps sometime (later) in a future version of `configuration-tools` we can consider how to make this less ad hoc.

**Comment by larskuhtz** [comment]
I have some ideas for configuration tools:
-   a minimal solution would be to document this as the "standard" way to define parsers,
-   in addition we could force this pattern by integrating the prefix parameter into the MParser type, or
-   we could come up with a broader story for representing the hierarchy of command line options in a similar way
  as in the configuration files. I would still vote for an solution that would use prefixes to command line
  options (possibly making use or improving upon the disambiguation logic already build into 
  optparse-applicative for convenience). In addition to that configuration-tools should provide parser
  modifiers for injecting the prefixes in the definition. I think optparse-applicative provides means to
  map over the parser tree, so maybe that could be used. Finally, the documentation (in particular
  the output of `--help`) should present the options in a more structured way. The cmdargs package
  provides a way to annotate options with grouping information, but it seems difficult to do something
  similar with optparse-applicative.

**Comment by jonsterling** [comment]
Thanks for laying out your thoughts... Definitely something to think about for the future.

In the meanwhile, I'm happy with the pull request as-is. The pattern of naming the prefixed version with an underscore is minimally disruptive...

**Comment by larskuhtz** [comment]
Thanks for the review @jonsterling!

**Pull request merged**
